/* eslint-disable max-len */
let presets = {};
presets["$$$ Royal - Mashup (197)"] = require("../presets/converted/$$$ Royal - Mashup (197).json");
presets["$$$ Royal - Mashup (431)"] = require("../presets/converted/$$$ Royal - Mashup (431).json");
presets["_Aderrasi - Wanderer in Curved Space - mash0000 - faclempt kibitzing meshuggana schmaltz (Geiss color mix)"] = require("../presets/converted/_Aderrasi - Wanderer in Curved Space - mash0000 - faclempt kibitzing meshuggana schmaltz (Geiss color mix).json");
presets["_Geiss - Artifact 01"] = require("../presets/converted/_Geiss - Artifact 01.json");
presets["_Geiss - Desert Rose 2"] = require("../presets/converted/_Geiss - Desert Rose 2.json");
presets["_Geiss - untitled"] = require("../presets/converted/_Geiss - untitled.json");
presets["_Mig_049"] = require("../presets/converted/_Mig_049.json");
presets["_Mig_085"] = require("../presets/converted/_Mig_085.json");
presets["_Rovastar + Geiss - Hurricane Nightmare (Posterize Mix)"] = require("../presets/converted/_Rovastar + Geiss - Hurricane Nightmare (Posterize Mix).json");
presets["Aderrasi + Geiss - Airhandler (Kali Mix) - Canvas Mix"] = require("../presets/converted/Aderrasi + Geiss - Airhandler (Kali Mix) - Canvas Mix.json");
presets["Aderrasi - Potion of Spirits"] = require("../presets/converted/Aderrasi - Potion of Spirits.json");
presets["Aderrasi - Songflower (Moss Posy)"] = require("../presets/converted/Aderrasi - Songflower (Moss Posy).json");
presets["Aderrasi - Storm of the Eye (Thunder) - mash0000 - quasi pseudo meta concentrics"] = require("../presets/converted/Aderrasi - Storm of the Eye (Thunder) - mash0000 - quasi pseudo meta concentrics.json");
presets["An AdamFX n Martin Infusion 2 flexi - Why The Sky Looks Diffrent Today - AdamFx n Martin Infusion - Tack Tile Disfunction B"] = require("../presets/converted/An AdamFX n Martin Infusion 2 flexi - Why The Sky Looks Diffrent Today - AdamFx n Martin Infusion - Tack Tile Disfunction B.json");
presets["cope + martin - mother-of-pearl"] = require("../presets/converted/cope + martin - mother-of-pearl.json");
presets["Cope - The Neverending Explosion of Red Liquid Fire"] = require("../presets/converted/Cope - The Neverending Explosion of Red Liquid Fire.json");
presets["Eo.S. + Phat - cubetrace - v2"] = require("../presets/converted/Eo.S. + Phat - cubetrace - v2.json");
presets["Eo.S. + Zylot - skylight (Stained Glass Majesty mix)"] = require("../presets/converted/Eo.S. + Zylot - skylight (Stained Glass Majesty mix).json");
presets["Eo.S. - glowsticks v2 05 and proton lights (+Krash′s beat code) _Phat_remix02b"] = require("../presets/converted/Eo.S. - glowsticks v2 05 and proton lights (+Krash′s beat code) _Phat_remix02b.json");
presets["fiShbRaiN + Flexi - witchcraft 2.0"] = require("../presets/converted/fiShbRaiN + Flexi - witchcraft 2.0.json");
presets["flexi + amandio c - organic [random mashup]"] = require("../presets/converted/flexi + amandio c - organic [random mashup].json");
presets["Flexi + amandio c - piercing 05 - Kopie (2) - Kopie"] = require("../presets/converted/Flexi + amandio c - piercing 05 - Kopie (2) - Kopie.json");
presets["flexi + fishbrain - neon mindblob grafitti"] = require("../presets/converted/flexi + fishbrain - neon mindblob grafitti.json");
presets["flexi + geiss - pogo cubes vs. tokamak vs. game of life [stahls jelly 4.5 finish]"] = require("../presets/converted/flexi + geiss - pogo cubes vs. tokamak vs. game of life [stahls jelly 4.5 finish].json");
presets["Flexi + Martin - astral projection"] = require("../presets/converted/Flexi + Martin - astral projection.json");
presets["Flexi + Martin - cascading decay swing"] = require("../presets/converted/Flexi + Martin - cascading decay swing.json");
presets["Flexi - alien fish pond"] = require("../presets/converted/Flexi - alien fish pond.json");
presets["Flexi - area 51"] = require("../presets/converted/Flexi - area 51.json");
presets["flexi - bouncing balls [double mindblob neon mix]"] = require("../presets/converted/flexi - bouncing balls [double mindblob neon mix].json");
presets["Flexi - infused with the spiral"] = require("../presets/converted/Flexi - infused with the spiral.json");
presets["Flexi - mindblob [shiny mix]"] = require("../presets/converted/Flexi - mindblob [shiny mix].json");
presets["Flexi - mindblob mix"] = require("../presets/converted/Flexi - mindblob mix.json");
presets["flexi - patternton, district of media, capitol of the united abstractions of fractopia"] = require("../presets/converted/flexi - patternton, district of media, capitol of the united abstractions of fractopia.json");
presets["Flexi - predator-prey-spirals"] = require("../presets/converted/Flexi - predator-prey-spirals.json");
presets["Flexi - smashing fractals [acid etching mix]"] = require("../presets/converted/Flexi - smashing fractals [acid etching mix].json");
presets["flexi - swing out on the spiral"] = require("../presets/converted/flexi - swing out on the spiral.json");
presets["Flexi - truly soft piece of software - this is generic texturing (Jelly) "] = require("../presets/converted/Flexi - truly soft piece of software - this is generic texturing (Jelly) .json");
presets["flexi - what is the matrix"] = require("../presets/converted/flexi - what is the matrix.json");
presets["Flexi, fishbrain, Geiss + Martin - tokamak witchery"] = require("../presets/converted/Flexi, fishbrain, Geiss + Martin - tokamak witchery.json");
presets["Flexi, martin + geiss - dedicated to the sherwin maxawow"] = require("../presets/converted/Flexi, martin + geiss - dedicated to the sherwin maxawow.json");
presets["Fumbling_Foo & Flexi, Martin, Orb, Unchained - Star Nova v7b"] = require("../presets/converted/Fumbling_Foo & Flexi, Martin, Orb, Unchained - Star Nova v7b.json");
presets["Geiss - Cauldron - painterly 2 (saturation remix)"] = require("../presets/converted/Geiss - Cauldron - painterly 2 (saturation remix).json");
presets["Geiss - Reaction Diffusion 2"] = require("../presets/converted/Geiss - Reaction Diffusion 2.json");
presets["Geiss - Thumb Drum"] = require("../presets/converted/Geiss - Thumb Drum.json");
presets["Geiss, Flexi + Stahlregen - Thumbdrum Tokamak [crossfiring aftermath jelly mashup]"] = require("../presets/converted/Geiss, Flexi + Stahlregen - Thumbdrum Tokamak [crossfiring aftermath jelly mashup].json");
presets["Krash + Illusion - Spiral Movement"] = require("../presets/converted/Krash + Illusion - Spiral Movement.json");
presets["Martin - acid wiring"] = require("../presets/converted/Martin - acid wiring.json");
presets["martin - angel flight"] = require("../presets/converted/martin - angel flight.json");
presets["martin - another kind of groove"] = require("../presets/converted/martin - another kind of groove.json");
presets["martin - bombyx mori"] = require("../presets/converted/martin - bombyx mori.json");
presets["Martin - charisma"] = require("../presets/converted/Martin - charisma.json");
presets["martin - disco mix 4"] = require("../presets/converted/martin - disco mix 4.json");
presets["martin - extreme heat"] = require("../presets/converted/martin - extreme heat.json");
presets["martin - ghost city"] = require("../presets/converted/martin - ghost city.json");
presets["martin - glass corridor"] = require("../presets/converted/martin - glass corridor.json");
presets["martin - infinity (2010 update)"] = require("../presets/converted/martin - infinity (2010 update).json");
presets["Martin - liquid arrows"] = require("../presets/converted/Martin - liquid arrows.json");
presets["martin - mandelbox explorer - high speed demo version"] = require("../presets/converted/martin - mandelbox explorer - high speed demo version.json");
presets["martin - mucus cervix"] = require("../presets/converted/martin - mucus cervix.json");
presets["martin - reflections on black tiles"] = require("../presets/converted/martin - reflections on black tiles.json");
presets["martin - stormy sea (2010 update)"] = require("../presets/converted/martin - stormy sea (2010 update).json");
presets["martin - The Bridge of Khazad-Dum"] = require("../presets/converted/martin - The Bridge of Khazad-Dum.json");
presets["martin [shadow harlequins shape code] - fata morgana"] = require("../presets/converted/martin [shadow harlequins shape code] - fata morgana.json");
presets["Milk Artist At our Best - FED - SlowFast Ft AdamFX n Martin - HD CosmoFX"] = require("../presets/converted/Milk Artist At our Best - FED - SlowFast Ft AdamFX n Martin - HD CosmoFX.json");
presets["ORB - Waaa"] = require("../presets/converted/ORB - Waaa.json");
presets["Phat+fiShbRaiN+Eo.S_Mandala_Chasers_remix"] = require("../presets/converted/Phat+fiShbRaiN+Eo.S_Mandala_Chasers_remix.json");
presets["Rovastar + Loadus + Geiss - FractalDrop (Triple Mix)"] = require("../presets/converted/Rovastar + Loadus + Geiss - FractalDrop (Triple Mix).json");
presets["Rovastar - Oozing Resistance"] = require("../presets/converted/Rovastar - Oozing Resistance.json");
presets["sawtooth grin roam"] = require("../presets/converted/sawtooth grin roam.json");
presets["shifter - dark tides bdrv mix 2"] = require("../presets/converted/shifter - dark tides bdrv mix 2.json");
presets["shifter - feathers (angel wings)"] = require("../presets/converted/shifter - feathers (angel wings).json");
presets["suksma - heretical crosscut playpen"] = require("../presets/converted/suksma - heretical crosscut playpen.json");
presets["suksma - Rovastar - Sunflower Passion (Enlightment Mix)_Phat_edit + flexi und martin shaders - circumflex in character classes in regular expression"] = require("../presets/converted/suksma - Rovastar - Sunflower Passion (Enlightment Mix)_Phat_edit + flexi und martin shaders - circumflex in character classes in regular expression.json");
presets["suksma - uninitialized variabowl (hydroponic chronic)"] = require("../presets/converted/suksma - uninitialized variabowl (hydroponic chronic).json");
presets["suksma - vector exp 1 - couldn′t not"] = require("../presets/converted/suksma - vector exp 1 - couldn′t not.json");
presets["TonyMilkdrop - Leonardo Da Vinci's Balloon [Flexi - merry-go-round + techstyle]"] = require("../presets/converted/TonyMilkdrop - Leonardo Da Vinci's Balloon [Flexi - merry-go-round + techstyle].json");
presets["Unchained & Rovastar - Wormhole Pillars (Hall of Shadows mix)"] = require("../presets/converted/Unchained & Rovastar - Wormhole Pillars (Hall of Shadows mix).json");
presets["Unchained - Rewop"] = require("../presets/converted/Unchained - Rewop.json");
presets["Unchained - Unified Drag 2"] = require("../presets/converted/Unchained - Unified Drag 2.json");
presets["yin - 191 - Temporal singularities"] = require("../presets/converted/yin - 191 - Temporal singularities.json");
presets["Zylot - Paint Spill (Music Reactive Paint Mix)"] = require("../presets/converted/Zylot - Paint Spill (Music Reactive Paint Mix).json");
presets["Zylot - Star Ornament"] = require("../presets/converted/Zylot - Star Ornament.json");
presets["Zylot - True Visionary (Final Mix)"] = require("../presets/converted/Zylot - True Visionary (Final Mix).json");
/* eslint-enable max-len */

export default class ButterchurnPresets {
  static getPresets () {
    return presets;
  }
}

module.exports = ButterchurnPresets;
