/* eslint-disable max-len */
let presets = {};
presets["$$$ Royal - Mashup (220)"] = require("../presets/converted/$$$ Royal - Mashup (220).json");
presets["_Aderrasi - Wanderer in Curved Space - mash0000 - faclempt kibitzing meshuggana schmaltz (Geiss color mix)"] = require("../presets/converted/_Aderrasi - Wanderer in Curved Space - mash0000 - faclempt kibitzing meshuggana schmaltz (Geiss color mix).json");
presets["_Geiss - Artifact 01"] = require("../presets/converted/_Geiss - Artifact 01.json");
presets["_Geiss - Desert Rose 2"] = require("../presets/converted/_Geiss - Desert Rose 2.json");
presets["_Geiss - untitled"] = require("../presets/converted/_Geiss - untitled.json");
presets["_Mig_049"] = require("../presets/converted/_Mig_049.json");
presets["_Rovastar + Geiss - Hurricane Nightmare (Posterize Mix)"] = require("../presets/converted/_Rovastar + Geiss - Hurricane Nightmare (Posterize Mix).json");
presets["Aderrasi + Geiss - Airhandler (Kali Mix) - Canvas Mix"] = require("../presets/converted/Aderrasi + Geiss - Airhandler (Kali Mix) - Canvas Mix.json");
presets["Aderrasi - Potion of Spirits"] = require("../presets/converted/Aderrasi - Potion of Spirits.json");
presets["Aderrasi - Songflower (Moss Posy)"] = require("../presets/converted/Aderrasi - Songflower (Moss Posy).json");
presets["Aderrasi - Storm of the Eye (Thunder) - mash0000 - quasi pseudo meta concentrics"] = require("../presets/converted/Aderrasi - Storm of the Eye (Thunder) - mash0000 - quasi pseudo meta concentrics.json");
presets["cope + martin - mother-of-pearl"] = require("../presets/converted/cope + martin - mother-of-pearl.json");
presets["Cope - The Neverending Explosion of Red Liquid Fire"] = require("../presets/converted/Cope - The Neverending Explosion of Red Liquid Fire.json");
presets["Eo.S. + Zylot - skylight (Stained Glass Majesty mix)"] = require("../presets/converted/Eo.S. + Zylot - skylight (Stained Glass Majesty mix).json");
presets["Eo.S. - glowsticks v2 05 and proton lights (+Krash′s beat code) _Phat_remix02b"] = require("../presets/converted/Eo.S. - glowsticks v2 05 and proton lights (+Krash′s beat code) _Phat_remix02b.json");
presets["fiShbRaiN + Flexi - witchcraft 2.0"] = require("../presets/converted/fiShbRaiN + Flexi - witchcraft 2.0.json");
presets["flexi + amandio c - organic [random mashup]"] = require("../presets/converted/flexi + amandio c - organic [random mashup].json");
presets["flexi + amandio c - organic12-3d-2.milk"] = require("../presets/converted/flexi + amandio c - organic12-3d-2.json");
presets["Flexi + amandio c - piercing 05 - Kopie (2) - Kopie"] = require("../presets/converted/Flexi + amandio c - piercing 05 - Kopie (2) - Kopie.json");
presets["flexi + fishbrain - neon mindblob grafitti"] = require("../presets/converted/flexi + fishbrain - neon mindblob grafitti.json");
presets["flexi + geiss - pogo cubes vs. tokamak vs. game of life [stahls jelly 4.5 finish]"] = require("../presets/converted/flexi + geiss - pogo cubes vs. tokamak vs. game of life [stahls jelly 4.5 finish].json");
presets["Flexi + Martin - astral projection"] = require("../presets/converted/Flexi + Martin - astral projection.json");
presets["Flexi + Martin - cascading decay swing"] = require("../presets/converted/Flexi + Martin - cascading decay swing.json");
presets["Flexi + stahlregen - jelly showoff parade"] = require("../presets/converted/Flexi + stahlregen - jelly showoff parade.json");
presets["Flexi - area 51"] = require("../presets/converted/Flexi - area 51.json");
presets["Flexi - infused with the spiral"] = require("../presets/converted/Flexi - infused with the spiral.json");
presets["Flexi - mindblob mix"] = require("../presets/converted/Flexi - mindblob mix.json");
presets["flexi - mom, why the sky looks different today"] = require("../presets/converted/flexi - mom, why the sky looks different today.json");
presets["flexi - patternton, district of media, capitol of the united abstractions of fractopia"] = require("../presets/converted/flexi - patternton, district of media, capitol of the united abstractions of fractopia.json");
presets["Flexi - predator-prey-spirals"] = require("../presets/converted/Flexi - predator-prey-spirals.json");
presets["Flexi - smashing fractals [acid etching mix]"] = require("../presets/converted/Flexi - smashing fractals [acid etching mix].json");
presets["flexi - swing out on the spiral"] = require("../presets/converted/flexi - swing out on the spiral.json");
presets["Flexi - truly soft piece of software - this is generic texturing (Jelly) "] = require("../presets/converted/Flexi - truly soft piece of software - this is generic texturing (Jelly) .json");
presets["flexi - what is the matrix"] = require("../presets/converted/flexi - what is the matrix.json");
presets["Fumbling_Foo & Flexi, Martin, Orb, Unchained - Star Nova v7b"] = require("../presets/converted/Fumbling_Foo & Flexi, Martin, Orb, Unchained - Star Nova v7b.json");
presets["Geiss + Flexi + Martin - disconnected"] = require("../presets/converted/Geiss + Flexi + Martin - disconnected.json");
presets["Geiss - Spiral Artifact"] = require("../presets/converted/Geiss - Spiral Artifact.json");
presets["Geiss, Flexi + Stahlregen - Thumbdrum Tokamak [crossfiring aftermath jelly mashup]"] = require("../presets/converted/Geiss, Flexi + Stahlregen - Thumbdrum Tokamak [crossfiring aftermath jelly mashup].json");
presets["Goody - The Wild Vort"] = require("../presets/converted/Goody - The Wild Vort.json");
presets["high-altitude basket unraveling - singh grooves nitrogen argon nz+"] = require("../presets/converted/high-altitude basket unraveling - singh grooves nitrogen argon nz+.json");
presets["martin + flexi - diamond cutter [prismaticvortex.com] - camille - i wish i wish i wish i was constrained"] = require("../presets/converted/martin + flexi - diamond cutter [prismaticvortex.com] - camille - i wish i wish i wish i was constrained.json");
presets["martin - angel flight"] = require("../presets/converted/martin - angel flight.json");
presets["martin - another kind of groove"] = require("../presets/converted/martin - another kind of groove.json");
presets["martin - bombyx mori"] = require("../presets/converted/martin - bombyx mori.json");
presets["martin - castle in the air"] = require("../presets/converted/martin - castle in the air.json");
presets["Martin - charisma"] = require("../presets/converted/Martin - charisma.json");
presets["martin - disco mix 4"] = require("../presets/converted/martin - disco mix 4.json");
presets["martin - frosty caves 2"] = require("../presets/converted/martin - frosty caves 2.json");
presets["martin - fruit machine"] = require("../presets/converted/martin - fruit machine.json");
presets["martin - ghost city"] = require("../presets/converted/martin - ghost city.json");
presets["martin - glass corridor"] = require("../presets/converted/martin - glass corridor.json");
presets["martin - infinity (2010 update)"] = require("../presets/converted/martin - infinity (2010 update).json");
presets["Martin - liquid arrows"] = require("../presets/converted/Martin - liquid arrows.json");
presets["martin - mucus cervix"] = require("../presets/converted/martin - mucus cervix.json");
presets["martin - stormy sea (2010 update)"] = require("../presets/converted/martin - stormy sea (2010 update).json");
presets["martin - The Bridge of Khazad-Dum"] = require("../presets/converted/martin - The Bridge of Khazad-Dum.json");
presets["martin, flexi, fishbrain + sto - enterstate [random mashup]"] = require("../presets/converted/martin, flexi, fishbrain + sto - enterstate [random mashup].json");
presets["ORB - Waaa"] = require("../presets/converted/ORB - Waaa.json");
presets["Phat+fiShbRaiN+Eo.S_Mandala_Chasers_remix"] = require("../presets/converted/Phat+fiShbRaiN+Eo.S_Mandala_Chasers_remix.json");
presets["Rovastar + Loadus + Geiss - FractalDrop (Triple Mix)"] = require("../presets/converted/Rovastar + Loadus + Geiss - FractalDrop (Triple Mix).json");
presets["Rovastar - Oozing Resistance"] = require("../presets/converted/Rovastar - Oozing Resistance.json");
presets["sawtooth grin roam"] = require("../presets/converted/sawtooth grin roam.json");
presets["shifter - dark tides bdrv mix 2"] = require("../presets/converted/shifter - dark tides bdrv mix 2.json");
presets["suksma - heretical crosscut playpen"] = require("../presets/converted/suksma - heretical crosscut playpen.json");
presets["suksma - Rovastar - Sunflower Passion (Enlightment Mix)_Phat_edit + flexi und martin shaders - circumflex in character classes in regular expression"] = require("../presets/converted/suksma - Rovastar - Sunflower Passion (Enlightment Mix)_Phat_edit + flexi und martin shaders - circumflex in character classes in regular expression.json");
presets["suksma - vector exp 1 - couldn′t not"] = require("../presets/converted/suksma - vector exp 1 - couldn′t not.json");
presets["TonyMilkdrop - Leonardo Da Vinci's Balloon [Flexi - merry-go-round + techstyle]"] = require("../presets/converted/TonyMilkdrop - Leonardo Da Vinci's Balloon [Flexi - merry-go-round + techstyle].json");
presets["TonyMilkdrop - Magellan's Nebula [Flexi - you enter first + multiverse]"] = require("../presets/converted/TonyMilkdrop - Magellan's Nebula [Flexi - you enter first + multiverse].json");
presets["Unchained - Unified Drag 2"] = require("../presets/converted/Unchained - Unified Drag 2.json");
presets["Zylot - Star Ornament"] = require("../presets/converted/Zylot - Star Ornament.json");
presets["Zylot - True Visionary (Final Mix)"] = require("../presets/converted/Zylot - True Visionary (Final Mix).json");
/* eslint-enable max-len */

export default class ButterchurnPresetsNonMinimal {
  static getPresets () {
    return presets;
  }
}
